version: "3.4"
services:
  sepolia-geth.dnp.dappnode.eth:
    image: "sepolia-geth.dnp.dappnode.eth:0.4.12"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.10.16
    volumes:
      - "sepolia:/sepolia"
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: always
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool"
      - SYNCMODE
volumes:
  sepolia: {}
