version: "3.5"
services:
  sepolia:
    image: "sepolia.sepolia-geth.public.dappnode.eth:0.1.3"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.10.20
    volumes:
      - "sepolia:/sepolia"
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: unless-stopped
    environment:
      - "EXTRA_OPTIONS=--http.api eth,engine,net,web3,txpool"
      - OVERRIDE_TTD=17000000000000000
      - SYNCMODE
volumes:
  sepolia: {}
