version: "3.5"
services:
  sepolia:
    image: "sepolia.sepolia-geth.dnp.dappnode.eth:0.1.0"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.11.6
    volumes:
      - "sepolia:/sepolia"
    ports:
      - "35415:35415"
      - "35415:35415/udp"
    restart: unless-stopped
    environment:
      - "EXTRA_OPTIONS=--http.api eth,engine,net,web3,txpool"
      - P2P_PORT=35415
      - SYNCMODE
volumes:
  sepolia: {}
